"""upgrade purchase table

Revision ID: 23fa4a8e177d
Revises: d0cf2e3b5b55
Create Date: 2023-04-12 16:23:01.961716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23fa4a8e177d'
down_revision = 'd0cf2e3b5b55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('expiry_date', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase', 'expiry_date')
    # ### end Alembic commands ###
