"""update sale model

Revision ID: 9b39476f6295
Revises: c262fb1857df
Create Date: 2023-04-14 10:21:12.496431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b39476f6295'
down_revision = 'c262fb1857df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sale_order',
    sa.Column('id', sa.Integer(), server_default=sa.text("nextval('sales_order_seq')"), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('sale', sa.Column('sale_order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sale', 'sale_order', ['sale_order_id'], ['id'])
    op.drop_column('sale', 'sales_order')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale', sa.Column('sales_order', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'sale', type_='foreignkey')
    op.drop_column('sale', 'sale_order_id')
    op.drop_table('sale_order')
    # ### end Alembic commands ###
