"""update sales table

Revision ID: c262fb1857df
Revises: 23fa4a8e177d
Create Date: 2023-04-14 09:31:11.077968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c262fb1857df'
down_revision = '23fa4a8e177d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale', sa.Column('sales_order', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sale', 'sales_order')
    # ### end Alembic commands ###
